### ISSUE TITLE
IDs with underline

### ISSUE THREAD

**Issue by webbird** [soatok/cupcake#13]
Having field IDs with an underline gives me strange results:

![2021-09-09 17_47_15-WBCE CMS Portable»Administration-Pages](https://user-images.githubusercontent.com/147354/132719223-48338015-c0a3-4107-945e-f3a352b5fe5d.png)

group_order => `group&lowbar;order`

Is this by design?

**Comment by soatok** [comment]
Yes, it's the consequence of `htmlentities()` being used to stop XSS.
